#!/usr/bin/env bash
# Bash script that installs nginx
# Listening on port for nginx is 80

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
