#!/usr/bin/env bash
# Configure Nginx to listen on port 80 made shorter
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
