#!/usr/bin/env bash
# Tells a story based on the contents of the /etc/passwd

while IFS=':' read -r username passwd uid gid userInfo home shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $passwd,"\
  "more info about the user here: $userInfo"
done < "/etc/passwd"
