#!/usr/bin/env bash
# Displays the current directory contents in list format
#   Displays only the part of the name after the first dash

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
